[book]
authors = ["rxdn", "Chaoskjell44"]
language = "en"
multilingual = false
src = "src"
title = "Hazel a Tickets Cat Docs"
description = "Official Documentation of the Hazel a Tickets Cat Discord Bot"

[output.html]
default-theme = "ayu"
