name: Deploy mdBook site to Pages

on:
  push:
    branches:
      - german-docs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          source $HOME/.cargo/env
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with mdBook
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifact
          path: ./book


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-artifact
          path: ./deployment-artifact
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 9eb2998e401a9f5376f8b98578b77c9e
          command: pages deploy ./deployment-artifact --project-name=docs-de
